name = "deltax"
type = "service"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# Cloudflare D1 Database 설정
[[d1_databases]]
binding = "DB"
database_name = "deltax-db"
database_id = "${CLOUDFLARE_D1_ID}"
