name = "deltax"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Cloudflare D1 Database 설정
[[d1_databases]]
binding = "DB"
database_name = "deltax-db"
database_id = "${CLOUDFLARE_D1_ID}"
