name = "deltax"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Cloudflare D1 Database 설정 (일단 ehdnd db입니다)
[[d1_databases]]
binding = "DB"
database_name = "my-db-name"
database_id = "a0637bbd-181c-4c6e-b52d-85557e3a1e1c"
